#!/usr/bin/env python3
"""Generate public-facing mod manifest docs from local launch config."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADMIN = ROOT / "admin"

MOD_FILES = {
    "chernarus": "chernarus_mods.txt",
    "enoch": "chernarus_mods.txt",
    "sakhal": "chernarus_mods.txt",
    "namalsk": "namalsk_mods.txt",
    "takistan": "takistan_mods.txt",
    "deerisle": "chernarus_mods.txt",
    "banov": "chernarus_mods.txt",
    "esseker": "chernarus_mods.txt",
    "rostow": "chernarus_mods.txt",
    "iztek": "chernarus_mods.txt",
    "alteria": "chernarus_mods.txt",
}


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def parse_mods_file(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8-sig").strip()
    return [item.strip() for item in text.split(";") if item.strip()]


def parse_meta(folder: str) -> dict:
    path = ROOT / folder / "meta.cpp"
    out = {"folder": folder, "name": folder.lstrip("@"), "workshop_id": ""}
    if not path.exists():
        return out
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    name = re.search(r'name\s*=\s*"([^"]+)"', text)
    published = re.search(r"publishedid\s*=\s*(\d+)", text)
    if name:
        out["name"] = name.group(1)
    if published:
        out["workshop_id"] = published.group(1)
    return out


def unique_mods(map_launch: dict) -> dict[str, dict]:
    mods: dict[str, dict] = {}
    for map_key, file_name in MOD_FILES.items():
        for folder in parse_mods_file(ADMIN / file_name):
            mods.setdefault(folder, parse_meta(folder))
            mods[folder].setdefault("maps", set()).add(map_key)

    for map_key, data in map_launch["maps"].items():
        for folder in data.get("prepend_mods", []) + data.get("extra_mods", []) + data.get("server_mods", []):
            mods.setdefault(folder, parse_meta(folder))
            mods[folder].setdefault("maps", set()).add(map_key)

    for entry in mods.values():
        entry["maps"] = sorted(entry.get("maps", []))
    return dict(sorted(mods.items(), key=lambda item: item[0].lower()))


def build_manifest() -> dict:
    map_launch = read_json(ADMIN / "map_launch.json")
    catalog = read_json(ADMIN / "map_workshop_catalog.json")
    mods = unique_mods(map_launch)

    maps = {}
    for key, data in map_launch["maps"].items():
        maps[key] = {
            "title": data["title"],
            "config_example": data["config"].replace(".cfg", ".example.cfg"),
            "mission_template": catalog.get(key, {}).get("mission_template", ""),
            "map_mod_folder": catalog.get(key, {}).get("server_mod_folder", ""),
            "workshop_id": catalog.get(key, {}).get("workshop_id", ""),
            "port": data["port"],
            "steam_query_port": data["steam_query_port"],
            "profiles_dir": data["profiles_dir"],
            "mods_file": data.get("mods_file", map_launch.get("mods_file", "")),
            "extra_mods": data.get("extra_mods", []),
            "server_mods": data.get("server_mods", []),
        }

    return {
        "generated_from": ["admin/map_launch.json", "admin/map_workshop_catalog.json", "admin/*_mods.txt", "@*/meta.cpp"],
        "maps": maps,
        "mods": list(mods.values()),
    }


def write_markdown(manifest: dict) -> None:
    lines = [
        "# Workshop Mods",
        "",
        "This file is generated by `python admin\\generate_public_docs.py` from local mod metadata and launch config.",
        "Workshop folders are not included in this repo; subscribe/download them through Steam and sync them locally.",
        "",
        "## Map Mods",
        "",
        "| Map | Workshop ID | Folder | Mission | Example Config | Ports |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for key, data in manifest["maps"].items():
        wid = data["workshop_id"] or "-"
        folder = data["map_mod_folder"] or "-"
        mission = data["mission_template"] or "-"
        ports = f"{data['port']} / query {data['steam_query_port']}"
        lines.append(f"| {key} | {wid} | `{folder}` | `{mission}` | `{data['config_example']}` | {ports} |")

    lines += [
        "",
        "## Shared Mods",
        "",
        "| Folder | Workshop ID | Name | Used By |",
        "| --- | --- | --- | --- |",
    ]
    for mod in manifest["mods"]:
        maps = ", ".join(mod["maps"]) if mod.get("maps") else "-"
        wid = mod["workshop_id"] or "unknown"
        lines.append(f"| `{mod['folder']}` | {wid} | {mod['name']} | {maps} |")

    lines += [
        "",
        "## Notes",
        "",
        "- VPP (`@VPPAdminTools`) is the standard admin tool in these presets.",
        "- Real `serverDZ*.cfg` files, keys, Workshop folders, logs, and player data are intentionally ignored.",
        "- Namalsk uses its server-side survival mod as `-serverMod`.",
        "- Imported map patrols are generated from seeded COT-style locations and can be refined with real COT exports.",
        "",
    ]
    (ROOT / "MODS.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    manifest = build_manifest()
    (ADMIN / "workshop_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    write_markdown(manifest)
    print("Wrote MODS.md and admin/workshop_manifest.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
